. "$HOME/.cargo/env"
export STARSHIP_CONFIG=/home/yuki/.config/starship.toml
export GTK_THEME=Catppuccin-Latte-Standard-Lavender-Light
export QT_QPA_PLATFORMTHEME=qt5ct
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export PATH="$PATH:/home/yuki/temp/eww/target/release"
# Deno
export DENO_INSTALL="/home/yuki/.deno"
export PATH="$DENO_INSTALL/bin:$PATH" 
# Bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
